# Configuration exports for Explainable AI
from .settings import (
    SCORE_THRESHOLDS,
    FEATURE_DESCRIPTIONS,
    WEIGHTS,
    FEATURE_NAMES,
    CONTRIBUTION_THRESHOLDS,
    CONFIDENCE_THRESHOLDS,
    EXPERIENCE_GAP_MAX,
    SENIORITY_GAP_MAX,
    SKILL_BREADTH_MAX
)

__all__ = [
    'SCORE_THRESHOLDS',
    'FEATURE_DESCRIPTIONS', 
    'WEIGHTS',
    'FEATURE_NAMES',
    'CONTRIBUTION_THRESHOLDS',
    'CONFIDENCE_THRESHOLDS',
    'EXPERIENCE_GAP_MAX',
    'SENIORITY_GAP_MAX',
    'SKILL_BREADTH_MAX'
]
